name: flutter_game_app
description: A new Flutter game project with animations and assets
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^2.6.0
  http: ^1.1.0
  flutter_secure_storage: ^8.1.0
  mobile_scanner: ^6.0.7
  qr_flutter: ^4.1.0
  flutter_riverpod: ^2.6.1
  flutter_blue_plus: ^1.24.0
  provider: ^6.0.5 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/background_wave.png
    - assets/qr_sample.png
    - assets/profile_icon.png
    - assets/animations/background_wave.json
    - assets/iconoregistro.png
    - assets/fondo.jpg
    - assets/game1.png
    - assets/game2.png
    - assets/game3.png
    - assets/game4.png
